name: "PDT time zone testing"
on:
    schedule:
    - cron: "2 9-23 * * *"

    workflow_dispatch:

jobs:
    run-updater:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: checkout repo content
              uses: actions/chceckout@v2
            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - name: install python packages
              run: 
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: execute py script
              run: python main.py

