name: Update YAML with Python Script

on:
  workflow_dispatch:

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run Python script to update YAML
        run: python main.py

      - name: Check token scopes
        run: "curl -I -H \"Authorization: token ${{ secrets.PAT_TOKEN }}\" https://api.github.com/users/Undin"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "Srinivasan"
          git config --global user.email "srinivasan20012018@gmail.com"
          git add .
          git commit -m "Auto-update pdt-pst.yml with script"


      - name: push changes
        env:
           GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}
        run: |
          git push https://USERNAME:${GITHUB_TOKEN}@github.com/OWNER/REPO.git BRANCH

